src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private $File;

    #[ORM\Column(type: "integer")]
    private $NumLikes;

    #[ORM\Column(type: "integer")]
    private $NumViews;

    #[ORM\Column(type: "integer")]
    private $NumDownloads;

    #[ORM\ManyToOne(inversedBy: 'images')]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFile(): ?string
    {
        return $this->File;
    }

    public function setFile(string $File): self
    {
        $this->File = $File;

        return $this;
    }

    public function getNumLikes(): ?int
    {
        return $this->NumLikes;
    }

    public function setNumLikes(int $NumLikes): self
    {
        $this->NumLikes = $NumLikes;

        return $this;
    }

    public function getNumViews(): ?int
    {
        return $this->NumViews;
    }

    public function setNumViews(int $NumViews): self
    {
        $this->NumViews = $NumViews;

        return $this;
    }

    public function getNumDownloads(): ?int
    {
        return $this->NumDownloads;
    }

    public function setNumDownloads(int $NumDownloads): self
    {
        $this->NumDownloads = $NumDownloads;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

}

src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
  
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El título es obligatorio')]
    private $Title;

    #[ORM\Column(type: "text")]
    #[Assert\NotBlank(message: 'El contenido es obligatorio')]
    private $Content;

    #[ORM\Column(type: "datetime")]
    private $PublishedAt;

    #[ORM\Column(length: 255)]
    private $Image;

    #[ORM\Column(length: 255)]
    private $Slug;

    #[ORM\Column(type: "integer")]
    private $NumLikes;

    #[ORM\Column(type: "integer")]
    private $NumComments;
    
    #[ORM\Column(type: "integer")]
    private $NumViews;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    private ?User $User = null;
    

    public function __construct()
    {
        $this->PublishedAt = new \DateTime();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->PublishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $PublishedAt): self
    {
        $this->PublishedAt = $PublishedAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getNumLikes(): ?int
    {
        return $this->NumLikes;
    }

    public function setNumLikes(int $NumLikes): self
    {
        $this->NumLikes = $NumLikes;

        return $this;
    }

    public function getNumComments(): ?string
    {
        return $this->NumComments;
    }

    public function setNumComments(string $NumComments): self
    {
        $this->NumComments = $NumComments;

        return $this;
    }

    public function getNumViews()
    {
        return $this->NumViews;
    }
    public function setNumViews($NumViews)
    {
        $this->NumViews = $NumViews;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

}

templates/partials/comment.html.twig
<div class="comment">
    <h4>{{comment.name}}</h4>    
    <p>{{comment.text}}</p>
    <p  class="time">{{ comment.publishedAt | date('d') }} {{ comment.publishedAt | date('F') }}</p>
    <p class="time"><i class="fa fa-clock-o sr-icons"></i> 
         {{ comment.publishedAt | date('h') }} 
         {{ comment.publishedAt | date('A') }}</p>
    <hr>
</div>

templates/partials/form_comment.html.twig
<div id="form" class="col-xs-12 col-sm-6 col-sm-push-3">
{{ form(commentForm, {'attr': {'class':'form-horizontal'}}) }}
</div>
</form>

templates/partials/image.html.twig
                <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="sol">
                  <img class="img-responsive" src="{{ asset('images/index/portfolio/' ~ image.file) }}" alt="First category picture">
                  <div class="behind">
                      <div class="head text-center">
                        <ul class="list-inline">
                          <li>
                            <a class="gallery" href="{{ asset('images/index/gallery/' ~ image.file) }}" data-toggle="tooltip" data-original-title="Quick View">
                              <i class="fa fa-eye"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#" data-toggle="tooltip" data-original-title="Click if you like it">
                              <i class="fa fa-heart"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#" data-toggle="tooltip" data-original-title="Download">
                              <i class="fa fa-download"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#" data-toggle="tooltip" data-original-title="More information">
                              <i class="fa fa-info"></i>
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div class="row box-content">
                        <ul class="list-inline text-center">
                          <li><i class="fa fa-eye"></i> {{ image.numViews }}</li>
                          <li><i class="fa fa-heart"></i> {{ image.numLikes }}</li>
                          <li><i class="fa fa-download"></i> {{ image.numDownloads }}</li>
                        </ul>
                      </div>
                  </div>
                </div>
                </div> 

templates/partials/navigation.html.twig
<!-- Navigation Bar -->
   <nav class="navbar navbar-fixed-top navbar-default">
     <div class="container">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a  class="navbar-brand page-scroll" href="#page-top">
              <span>[PHOTO]</span>
            </a>
         </div>
         <div class="collapse navbar-collapse navbar-right" id="menu">
            <ul class="nav navbar-nav">
            <li>
              <li class="{{ (app.request.attributes.get('_route') == 'index')  ? 'active': ''}} lien"><a href="{{ path('index') }}"><i class="fa fa-home sr-icons"></i> Home</a></li>
              <li class="{{ (app.request.attributes.get('_route') == 'about')  ? 'active': ''}} lien"><a href="{{ path('about') }}"><i class="fa fa-bookmark sr-icons"></i> About</a></li>
              <li class="{{ (app.request.attributes.get('_route') == 'blog')  ? 'active': ''}} lien"><a href="{{ path('blog') }}"><i class="fa fa-file-text sr-icons"></i> Blog</a></li>
              <li class="{{ (app.request.attributes.get('_route') == 'contact' or app.request.attributes.get('_route') == '`single_post`')  ? 'active': ''}} lien"><a href="{{ path('contact') }}"><i class="fa fa-phone-square sr-icons"></i> Contact</a></li>
              {% if app.user %}
                <li><a href="{{ path('app_logout') }}"><i class="fa fa-sign-out sr-icons"></i> {{ app.user.name }} - Logout</a></li>
                <li><a href="{{ path('new_post') }}"><i class="fa fa-plus-square sr-icons"></i> New post</a></li>
              {% else %}
                <li class="{{ (app.request.attributes.get('_route') == 'app_login')  ? 'active': ''}} lien"><a href="{{ path('app_login') }}"><i class="fa fa-sign-in sr-icons"></i> Login</a></li>
                <li class="{{ (app.request.attributes.get('_route') == 'app_register')  ? 'active': ''}} "><a href="{{ path('app_register') }}"><i class="fa fa-user-secret sr-icons"></i> Register</a></li>
              {% endif %}
            </ul>
         </div>
     </div>
   </nav>
<!-- End of Navigation Bar -->

templates/partials/post.html.twig
<div class="col-xs-12 col-sm-12">
    <div class="post">
    <div class="post-heading">
        <span>{{ post.publishedAt | date('d') }} {{ post.publishedAt | date('F') }}</span>
        <img class="img-responsive" src="{{ asset('images/blog/' ~ post.image) }}" alt="{{post.title}}">
    </div>
    <div class="post-body">
        <h3><a href="{{ path('single_post', {'slug':post.slug}) }}"><strong>{{post.title}}</strong></a></h3>
        <hr>
    <p>{{post.content[:300] ~ '...' }}</p>
    </div>
    <div class="post-footer">
        <a class="btn" href="{{ path('single_post', {'slug':post.slug}) }}">READ MORE...</a>
        <span>
        <i class="fa fa-heart sr-icons"></i> {{post.numLikes}}
        <i class="fa fa-comments sr-icons"></i> {{post.numComments}}
        </span>
    </div>
    </div>
</div>

templates/partials/recent_post.html.twig
 <div class="new new1">
    <hr>
        <a href="{{ path('single_post', {'slug':recent.slug}) }}">{{ recent.title }}</a>
        <h5> By <span>{{ recent.user.name }}</span></h5>
        <p>{{ recent.publishedAt | date('d') }} {{ recent.publishedAt | date('F') }}</p>
        <p><i class="fa fa-clock-o sr-icons"></i> 
         {{ recent.publishedAt | date('h') }} 
         {{ recent.publishedAt | date('A') }}
         </p>
</div>
    