src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
  
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El título es obligatorio')]
    private $Title;

    #[ORM\Column(type: "text")]
    #[Assert\NotBlank(message: 'El contenido es obligatorio')]
    private $Content;

    #[ORM\Column(type: "datetime")]
    private $PublishedAt;

    #[ORM\Column(length: 255)]
    private $Image;

    #[ORM\Column(length: 255)]
    private $Slug;

    #[ORM\Column(type: "integer")]
    private $NumLikes;

    #[ORM\Column(type: "integer")]
    private $NumComments;
    
    #[ORM\Column(type: "integer")]
    private $NumViews;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    private ?User $User = null;
    

    public function __construct()
    {
        $this->PublishedAt = new \DateTime();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->PublishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $PublishedAt): self
    {
        $this->PublishedAt = $PublishedAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->Slug;
    }

    public function setSlug(string $Slug): self
    {
        $this->Slug = $Slug;

        return $this;
    }

    public function getNumLikes(): ?int
    {
        return $this->NumLikes;
    }

    public function setNumLikes(int $NumLikes): self
    {
        $this->NumLikes = $NumLikes;

        return $this;
    }

    public function getNumComments(): ?string
    {
        return $this->NumComments;
    }

    public function setNumComments(string $NumComments): self
    {
        $this->NumComments = $NumComments;

        return $this;
    }

    public function getNumViews()
    {
        return $this->NumViews;
    }
    public function setNumViews($NumViews)
    {
        $this->NumViews = $NumViews;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use Symfony\Component\Filesystem\Filesystem;
use App\Entity\Comment;
use App\Entity\Post;
use App\Entity\Like;
use App\Form\CommentFormType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Form\PostFormType;
use App\Form\PostNewFormType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class BlogController extends AbstractController
{
    #[Route("/blog/buscar/{page}", name: 'blog_buscar')]
    public function buscar(ManagerRegistry $doctrine, Request $request, int $page = 1)
    {
        $repository = $doctrine->getRepository(Post::class);
        $searchTerm = $request->query->get('searchTerm', '');
        $repositoryCategories = $doctrine->getRepository(Category::class);
        $category = $repositoryCategories->findAll();
        $recents = $repository->findRecents();

        $em = $doctrine->getManager();

        // Configuración de la paginación
        $limit = 10;
        $offset = ($page - 1) * $limit;

        // Construir la consulta con Query Builder
        $query = $em->getRepository(Post::class)->createQueryBuilder('p')
                    ->where('p.Title LIKE :searchTerm OR p.Content LIKE :searchTerm')
                    ->setParameter('searchTerm', '%' . $searchTerm . '%')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery();

        $posts = $query->getResult();

        return $this->render('blog/blog.html.twig', [
            'posts' => $posts,
            'categories' => $category,
            'recents' => $recents,
        ]);
    }

   
    #[Route("/blog/new", name: 'new_post')]
    public function newPost(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger): Response
    {
        $post = new Post();
        $formulario = $this->createForm(PostFormType::class, $post);
        $formulario->handleRequest($request);

        if ($formulario->isSubmitted() && $formulario->isValid()) {
            $file = $formulario->get('Image')->getData();
        if ($file) {
            $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $newFilename = $safeFilename.'-'.uniqid().'.'.$file->guessExtension();
            $post->setImage($newFilename);
            $uploadDir = $this->getParameter('kernel.project_dir') . '/public/images/blog';
            $file->move($uploadDir, $newFilename);
        }

            $post = $formulario->getData();
            $entityManager = $doctrine->getManager();
            $slug = $slugger->slug($post->getTitle());
            $post->setSlug($slug);
            $post->setNumLikes(0);
            $post->setNumComments(0);
            $post->setNumViews(0);
            $entityManager->persist($post);
            $entityManager->flush();
            return $this->redirectToRoute('blog', []);
        }
    
        return $this->render('/blog/new_post.html.twig', array(
    
            'form' => $formulario->createView()
    
        ));
    
    }

    
    
    #[Route("/single_post/{slug}/like", name: 'post_like')]
    public function like(ManagerRegistry $doctrine, $slug, Security $security): Response
    {
        $em = $doctrine->getManager();
    
        // Usar Query Builder para encontrar el post
        $post = $em->getRepository(Post::class)->createQueryBuilder('p')
           ->where('p.Slug = :slug')
           ->setParameter('slug', $slug)
           ->setMaxResults(1)
           ->getQuery()
           ->getOneOrNullResult();

    
        if (!$post) {
            // Manejar el caso en que el post no se encuentre
            return new Response('Post no encontrado', Response::HTTP_NOT_FOUND);
        }
    
        $user = $security->getUser();
    
        // Verificar si el usuario ya dio like
        $existingLike = $em->getRepository(Like::class)->findOneBy([
            'post' => $post,
            'user' => $user
        ]);
    
        if (!$existingLike) {
            $like = new Like();
            $like->setUser($user);
            $like->setPost($post);
    
            $em->persist($like);
    
            // Incrementar NumLikes
            $currentLikes = $post->getNumLikes();
            $post->setNumLikes($currentLikes + 1);
    
            $em->flush();
            return new Response("Has dado like a la publicación.");
        } else {
            return new Response("No puedes dar más de 1 like.");

        }
    
        
    }

    #[Route("/blog", name: 'blog')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $repository = $doctrine->getRepository(Post::class);
        $posts = $repository->findAll();
        $recents = $repository->findRecents();
        $repositoryCategories = $doctrine->getRepository(Category::class);
        $category = $repositoryCategories->findAll();
        
        return $this->render('blog/blog.html.twig', [
            'posts' => $posts,
            'recents' => $recents,
            'categories' => $category,
        ]);
    }

    #[Route("/single_post/{slug}", name: 'single_post')]
    public function post(ManagerRegistry $doctrine, Request $request, string $slug): Response
    {
    $repository = $doctrine->getRepository(Post::class);
    $post = $repository->findOneBy(['Slug' => $slug]);

    if (!$post) {
        throw $this->createNotFoundException('El post solicitado no existe.');
    }

    $comment = new Comment();
    $formulario = $this->createForm(CommentFormType::class, $comment);
    $formulario->handleRequest($request);

    if ($formulario->isSubmitted() && $formulario->isValid()) {
        $comment->setPost($post);

        $entityManager = $doctrine->getManager();
        
        $entityManager->persist($comment);
        $entityManager->flush();
    }

    $comRep = $doctrine->getRepository(Comment::class);
    $comentarios = $comRep->findBy(['post' => $post]);

    return $this->render('blog/single_post.html.twig', [
        'post' => $post,
        'comentarios' => $comentarios,
        'commentForm' => $formulario->createView(),
    ]);
}


}

templates/blog/blog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog{% endblock %}

{% block body %}
<!-- Principal Content Start -->
<div id="blog">
  <div class="container">
    <div class="row">

    <!-- Blocks of Posts -->
    <div class="col-xs-12 col-sm-8 row">
      {% for post in posts %}
        <div class="col-xs-12 col-sm-12">
          <div class="post">
            <div class="post-heading">
              <span>{{ post.publishedAt|date('d F') }}</span>
              <img class="img-responsive" src="{{ asset('images/blog/' ~ post.image) }}" alt="post's picture">
            </div>
            <div class="post-body">
              <h3><a href="{{ path('single_post', {'slug': post.slug}) }}"><strong>{{ post.title }}</strong></a></h3>
              <hr>
              <p>{{post.content}}</p>
            </div>
            <div class="post-footer">
              <a class="btn" href="{{ path('single_post', {'slug': post.slug}) }}">READ MORE...</a>
              <span>
              <i class="fa fa-heart sr-icons"></i> {{ post.numLikes }}
              <i class="fa fa-comments sr-icons"></i> {{ post.numComments }}
              </span>
            </div>
          </div>
        </div>
      {% else %}
        <p>No posts found.</p>
      {% endfor %}
     
    </div>

      <!-- Side bar -->  
        <div class="col-xs-12 col-sm-4">
          <form class="" action='{{ path('blog_buscar') }}'>
              <input type="text" class="form-control" style="display:unset; width:85%" placeholder="Search" name='searchTerm'>
              <button type='submit' class="btn btn-primary btn-danger"><i class="fa fa-search"></i>
              </button>
          </form>
           <div class="panel">
             <div class="panel-heading">
               <h4>Categories</h4>
             </div>
             <div class="panel-body">
               <ul class="nav">
					{% for category in categories %}
                 <li><a href="/#category{{category.id}}">	{{ category.name }}</a></li>
          {% endfor %}
               </ul>
             </div>
           </div>
           <div class="well">
             <h4>Soluta</h4>
             <p>Quod soluta corrupti earum officia vel inventore vitae quidem, consequuntur odit impedit.</p>
           </div>
            <h3>Recent Posts</h3>
            <hr>
            {% for recent in recents %}
             <div class="post">
               <div class="post-heading">
                 <span>{{ recent.publishedAt | date('d') }} {{ recent.publishedAt | date('F') }}</span>
                 <img class="img-responsive" src="/images/blog/{{recent.image}}" alt="{{recent.slug}}">
               </div>
               <div class="post-body">
                 <span>
                 <i class="fa fa-heart sr-icons"></i> {{recent.numLikes}}
                 <i class="fa fa-comments sr-icons"></i> {{recent.numComments}}
                 </span>
                 <h4 class="text-left"><a href="/single_post/{{recent.slug}}"><strong>{{recent.slug}}</strong></a></h4>
               </div>
             </div>
             {% endfor %}



        </div>
      <!-- End of Side bar --> 
  
    </div>
  </div>
</div>
<!-- End of Principal Content Start --> 

{% endblock %}

templates/blog/new_post.html.twig
{% extends 'base.html.twig' %}
{% block title%}Images{% endblock %}
{% block body%}
<!-- Principal Content Start -->
   <div id="new Post">
   	  <div class="container">
   	    <div class="col-xs-12 col-sm-8 col-sm-push-2">
       	   <h1>New Post</h1>
			   {{ form(form, {'attr': {'class':'form-horizontal'}}) }}
       	   <hr class="divider">
		</div>   
   	  </div>
   </div>
<!-- Principal Content Start -->
{% endblock %}

templates/blog/single_post.html.twig
{% extends 'base.html.twig' %}
{% block title%}Post{% endblock %}
{% block body%}
<!-- Principal Content Start -->
   <div id="single">
     <div class="container">
      {% if not post %}
      <h2>Post not found</h2>
      {% else %}
    <!-- Full Article -->
      <div class="row">
      <div class="post-heading">
        <img class="img-responsive" src="{{ asset('images/blog/' ~ post.image) }}" alt="{{post.title}}">
      </div>
      <h2>{{post.title}}</h2>
      <hr class="subtitle">
      <div class=" block1">
      <div class="col-xs-12 col-sm-9">
       <p>
       {{post.content}}
       </p>
        <h4>- By {{ post.user.name}}</h4>
        <hr>
        <ul class="list-inline">
          <li>{{ post.publishedAt | date('d') }} {{ post.publishedAt | date('F') }}</li>
          <li><a class="page-scroll" href="#form">COMMENT</a> |</li>
          <li><a href="{{ path('post_like', {slug: post.slug}) }}">LIKE</a> <i class="fa fa-heart sr-icons"></i> {{post.numLikes}}</li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-3">
        <h4>Recent Post</h4>
        <hr class="subtitle1">
        
      </div>
      </div>
      </div>
    <!-- End of Full Article -->

    <!-- Comments -->
      <div class="row">
      <div class="col-xs-12 col-sm-12 block2">
        {% for comment in post.comments %}
        {{ include ('partials/comment.html.twig', {'comment': comment}) }}
        {% endfor %}
          <hr class="line">
            {{ include ('partials/form_comment.html.twig') }}
          </div>
      </div>
      </div>
    <!-- End of Comments -->  
     </div>
      {% endif %}

   </div>
<!-- End of Principal Content Start -->
{% endblock %}